config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"

  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follower', to: 'relationships#follower'
    get 'followed', to: 'relationships#followed'
    # resources :chats, only: [:show, :create]
  end

  get 'search', to: 'searches#search'

  get 'chats/:id', to: 'chats#show', as: :chat_show
  post 'chats/:id', to: 'chats#create', as: :chat_create
  # resources :chats, only: [:show, :create]



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :followers, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followeds, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy


  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length:{maximum:50}
  validates :introduction, presence:true, :on => :update

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow_to?(user)
    followers.exists?(followed_id: user.id)
  end

  def follow_each_other?(user)
    self.follow_to?(user) && user.follow_to?(self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followeds.count %></td>
        <td>
        <% if user != current_user %>
          <% if current_user.follow_to?(user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
            フォロー外す
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
            フォローする
            <% end %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<%= javascript_pack_tag 'user-info' %>

<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to user_follower_path(user) do %>
	    <%= user.followers.count %></th>
	    <% end %>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to user_followed_path(user) do %>
	    <%= user.followeds.count %></th>
	    <% end %>
  </tr>
</table>

<div class='row'>
  <div class="col-6">
  <% if @user.nil? || @user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.follow_to?(user) %>
      <%= link_to user_relationships_path(user), class: "btn btn-info btn-block follow_user_#{user.id}", method: :delete do %>
      フォローを外す
      <% end %>
    <% else %>
      <%= link_to user_relationships_path(user), class: "btn btn-success btn-block follow_user_#{user.id}", method: :post do %>
      フォローする
      <% end %>
    <% end %>
  <% end %>
  </div>
  <div class="col-6 chat-link">
    <% if user != current_user && current_user.follow_each_other?(user) %>
      <%= link_to chat_show_path(user) do %>
      chatを始める
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div id="update-user-container" class="container">
  <div class="row">
    <div class="col px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render "layouts/errors", obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: "image/*" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4 main-left">
      <h2>User info</h2>
      <%= render "info", user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 main-right">
      <h2>Users</h2>
      <%= render "index",users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-4 main-left'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 main-right'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>